source: null
include_update: false
include_test: true
num_few_shot_examples: 4
few_shot_example_pool_size: 5
num_public_unit_tests: 1

num_unit_tests_fewshot: 1
few_shot_examples_strategy: diff
random_few_shot_examples: True