defaults:
  - lora: default
  - _self_

model_name_or_path:
# Quantization
load_in_8bit: False
load_in_4bit: False
bnb_4bit_compute_dtype:
bnb_4bit_quant_type: "fp4"
bnb_4bit_use_double_quant: False

# # LoRA
# lr: 2e-4
# batch_size: 4
# num_epoch: 10
# decay: 1e-8