defaults:
  - data: finetune
  - model: finetune
  - generation: prepend
  - prompt: finetune
  - evaluation: finetune
  - training: lora
  - _self_

data:
  # data_dir: /Users/leoliu/proj/tool-KE/data/swap
  data_dir: /home/zliu/zliu/tool-KE/data/swap
model:
  # model_name_or_path: /Users/leoliu/proj/shared_resources/CodeLlama-7b-Python-hf
  model_name_or_path: /home/zliu/shared_resources/models/llama2/hf/CodeLlama-7b-Instruct-hf

output_dir:
chkpt_dir: 

seed: 42
# gpu_id: 0
debug: false
rerun_eval: false