defaults:
  - data: finetune
  - model: lora
  - generation: prepend
  - prompt: finetune
  - evaluation: default
  - training: lora
  - _self_



training: 
  batch_size: 8
model:
  # model_name_or_path: /Users/leoliu/proj/shared_resources/CodeLlama-7b-Python-hf
  model_name_or_path: /u/zliu/datastor1/shared_resources/models/llama2/hf/CodeLlama-7b-Instruct-hf

output_dir: tmp/chkpt_null

data:
  # data_dir: /Users/leoliu/proj/tool-KE/data/swap
  data_dir: data/prelim/pilot_run/gpt-4/13-functions-3-calls-w-v2.1-fixed-auto_select/prog_syn_v2.1-first_draft
  inspect_dir: tmp_inspect_ft
  training_example_per_update: 1
  test_example_per_update: 1
  

prompt:
  train_source: prompts/instruction_style_ft_k_ps.jinja2
  eval_source: prompts/instruction_style_ft_k_ps.jinja2
  include_update: true
  num_few_shot_examples: 1
  num_public_unit_tests: 1

seed: 42
# gpu_id: 0
debug: false
rerun_eval: false