defaults:
  - data: prepend
  - model: lora
  - generation: prepend
  - prompt: finetune
  - evaluation: default
  - training: lora
  - _self_

model:
  model_name_or_path: # hf model id or path to model

data:
  data_dir: leo-liuzy/CodeUpdateArena
  training_example_per_update: 0

output_dir: tmp/chkpt_null

prompt:
  train_source: prompts/instruction_style_ft_no_ps_train.jinja2
  eval_source: prompts/instruction_style_ft_no_ps_eval.jinja2

usage: eval

seed: 42
debug: false
rerun_eval: false