defaults:
  - data: prepend
  - model: lora
  - generation: prepend
  - prompt: finetune
  - evaluation: default
  - training: lora
  - _self_


training: 
  batch_size: 8

model:
  model_name_or_path: /u/zliu/datastor1/shared_resources/models/llama2/hf/CodeLlama-7b-Instruct-hf

output_dir: tmp/chkpt_null

data:
  data_dir: data/prelim/CodeUpdateArena-after-dedup
  training_example_per_update: 1
  test_example_per_update: 1
  

prompt:
  train_source: prompts/instruction_style_ft_k_ps.jinja2
  eval_source: prompts/humaneval.jinja2

usage: 

seed: 42
debug: false
rerun_eval: false