defaults:
  - data: prepend
  - model: lora
  - generation: prepend
  - prompt: finetune
  - evaluation: default
  - training: lora
  - _self_

model:
  model_name_or_path: /u/zliu/datastor1/shared_resources/models/llama2/hf/CodeLlama-7b-Instruct-hf

output_dir: tmp/chkpt_null

data:
  data_dir: data/prelim/CodeUpdateArena-after-dedup
  training_example_per_update: 0

prompt:
  train_source: prompts/instruction_style_ft_no_ps_train.jinja2
  eval_source: prompts/instruction_style_ft_no_ps_eval.jinja2

usage: eval

seed: 42
debug: false
rerun_eval: false