defaults:
  - data: finetune
  - model: lora
  - generation: prepend
  - prompt: finetune
  - evaluation: default
  - training: lora
  - _self_



training: 
  batch_size: 8
  lr: 1e-3

model:
  model_name_or_path: <path to checkpoint directory>

evaluation:
  n_decoding_example: 5

output_dir: tmp/chkpt_null

data:
  data_dir: data/prelim/CodeUpdateArena-after-dedup
  training_example_per_update: 2
  

prompt:
  train_source: prompts/instruction_style_ft_k_ps.jinja2
  eval_source: prompts/humaneval.jinja2
  include_update: true
  num_few_shot_examples: 1
  num_public_unit_tests: 1

usage: 

seed: 42
# gpu_id: 0
debug: false
rerun_eval: false