defaults:
  - data: prepend
  - model: prepend
  - generation: prepend
  - prompt: zero-shot
  - evaluation: default
  - _self_

data:
  data_dir: data/prelim/CodeUpdateArena-after-dedup

model:
  model_name_or_path: /u/zliu/datastor1/shared_resources/models/deepseek/deepseek-coder-7b-instruct-v1.5

output_dir:

prompt:
  source: prompts/instruction_style_one_shot.jinja2

seed: 42
debug: false
rerun_eval: false