defaults:
  - data: prepend
  - model: prepend
  - generation: prepend
  - prompt: zero-shot
  - evaluation: default
  - _self_

model:
  model_name_or_path: # hf model id or path to model

data:
  data_dir: # hf dataset id or path to data

output_dir:

prompt:
  source: prompts/instruction_style_one_shot.jinja2

seed: 42
debug: false
rerun_eval: false